<?php

namespace Database\Seeders;

use App\Models\Medicine;
use App\Models\Supplier;
use Illuminate\Database\Seeder;

class ObatSeeder extends Seeder
{
    public function run(): void
    {
        $defaultSupplier = Supplier::firstOrCreate(
            ['nama_supplier' => 'CV Sumber Sehat Medika'],
            [
                'alamat' => 'Jl. Dr. Sutomo No. 42, Bandung',
                'telepon' => '022-7213344',
            ]
        );

        $suppliers = Supplier::pluck('id', 'nama_supplier');

        $obat = [
            // Analgesik & Antiinflamasi
            [
                'supplier' => 'PT Kimia Farma Trading',
                'kode_obat' => 'OBT-001',
                'nama_obat' => 'Paracetamol 500mg (Sanmol)',
                'kategori' => 'Analgesik',
                'satuan' => 'strip',
                'harga_beli' => 3500,
                'harga_jual' => 6000,
                'stok' => 120,
                'stok_minimum' => 25,
                'tanggal_expired' => now()->addMonths(14)->toDateString(),
                'prioritas_owner' => 5,
            ],
            [
                'supplier' => 'PT Kimia Farma Trading',
                'kode_obat' => 'OBT-002',
                'nama_obat' => 'Asam Mefenamat 500mg',
                'kategori' => 'Analgesik',
                'satuan' => 'strip',
                'harga_beli' => 4500,
                'harga_jual' => 7500,
                'stok' => 95,
                'stok_minimum' => 20,
                'tanggal_expired' => now()->addMonths(16)->toDateString(),
                'prioritas_owner' => 4,
            ],
            [
                'supplier' => 'PT Kimia Farma Trading',
                'kode_obat' => 'OBT-003',
                'nama_obat' => 'Ibuprofen 400mg',
                'kategori' => 'Analgesik',
                'satuan' => 'strip',
                'harga_beli' => 8000,
                'harga_jual' => 13000,
                'stok' => 70,
                'stok_minimum' => 15,
                'tanggal_expired' => now()->addMonths(8)->toDateString(),
                'prioritas_owner' => 4,
            ],
            [
                'supplier' => 'PT Anugerah Pharmindo Lestari',
                'kode_obat' => 'OBT-004',
                'nama_obat' => 'Bodrex Extra Strip',
                'kategori' => 'Analgesik',
                'satuan' => 'strip',
                'harga_beli' => 5000,
                'harga_jual' => 8000,
                'stok' => 110,
                'stok_minimum' => 20,
                'tanggal_expired' => now()->addMonths(20)->toDateString(),
                'prioritas_owner' => 3,
            ],
            [
                'supplier' => 'PT Anugerah Pharmindo Lestari',
                'kode_obat' => 'OBT-005',
                'nama_obat' => 'Paramex Tablet Strip',
                'kategori' => 'Analgesik',
                'satuan' => 'strip',
                'harga_beli' => 3000,
                'harga_jual' => 5000,
                'stok' => 130,
                'stok_minimum' => 20,
                'tanggal_expired' => now()->addMonths(22)->toDateString(),
                'prioritas_owner' => 3,
            ],
            [
                'supplier' => 'PT Anugerah Pharmindo Lestari',
                'kode_obat' => 'OBT-006',
                'nama_obat' => 'Panadol Extra Merah',
                'kategori' => 'Analgesik',
                'satuan' => 'strip',
                'harga_beli' => 10000,
                'harga_jual' => 15000,
                'stok' => 100,
                'stok_minimum' => 30,
                'tanggal_expired' => now()->addMonths(12)->toDateString(),
                'prioritas_owner' => 5,
            ],
            [
                'supplier' => 'PT Kimia Farma Trading',
                'kode_obat' => 'OBT-007',
                'nama_obat' => 'Antalgin 500mg',
                'kategori' => 'Analgesik',
                'satuan' => 'strip',
                'harga_beli' => 4000,
                'harga_jual' => 6500,
                'stok' => 85,
                'stok_minimum' => 15,
                'tanggal_expired' => now()->addMonths(18)->toDateString(),
                'prioritas_owner' => 3,
            ],

            // Antibiotik
            [
                'supplier' => 'PT Enseval Putera Megatrading',
                'kode_obat' => 'OBT-008',
                'nama_obat' => 'Amoxicillin 500mg',
                'kategori' => 'Antibiotik',
                'satuan' => 'strip',
                'harga_beli' => 11000,
                'harga_jual' => 17000,
                'stok' => 90,
                'stok_minimum' => 20,
                'tanggal_expired' => now()->addMonths(10)->toDateString(),
                'prioritas_owner' => 5,
            ],
            [
                'supplier' => 'PT Enseval Putera Megatrading',
                'kode_obat' => 'OBT-009',
                'nama_obat' => 'Cefadroxil 500mg',
                'kategori' => 'Antibiotik',
                'satuan' => 'strip',
                'harga_beli' => 16000,
                'harga_jual' => 24000,
                'stok' => 80,
                'stok_minimum' => 15,
                'tanggal_expired' => now()->addMonths(11)->toDateString(),
                'prioritas_owner' => 5,
            ],
            [
                'supplier' => 'PT Enseval Putera Megatrading',
                'kode_obat' => 'OBT-010',
                'nama_obat' => 'Ciprofloxacin 500mg',
                'kategori' => 'Antibiotik',
                'satuan' => 'strip',
                'harga_beli' => 13000,
                'harga_jual' => 20000,
                'stok' => 75,
                'stok_minimum' => 12,
                'tanggal_expired' => now()->addMonths(15)->toDateString(),
                'prioritas_owner' => 4,
            ],
            [
                'supplier' => 'PT Enseval Putera Megatrading',
                'kode_obat' => 'OBT-011',
                'nama_obat' => 'FG Troches Meiji Tablet',
                'kategori' => 'Antibiotik',
                'satuan' => 'strip',
                'harga_beli' => 15000,
                'harga_jual' => 22000,
                'stok' => 95,
                'stok_minimum' => 25,
                'tanggal_expired' => now()->addMonths(9)->toDateString(),
                'prioritas_owner' => 5,
            ],

            // Antihistamin & AntiAlergi
            [
                'supplier' => 'PT Anugerah Pharmindo Lestari',
                'kode_obat' => 'OBT-012',
                'nama_obat' => 'Cetirizine 10mg',
                'kategori' => 'Antihistamin',
                'satuan' => 'strip',
                'harga_beli' => 5500,
                'harga_jual' => 9000,
                'stok' => 100,
                'stok_minimum' => 15,
                'tanggal_expired' => now()->addMonths(15)->toDateString(),
                'prioritas_owner' => 4,
            ],
            [
                'supplier' => 'PT Kimia Farma Trading',
                'kode_obat' => 'OBT-013',
                'nama_obat' => 'CTM (Chlorpheniramine) 4mg',
                'kategori' => 'Antihistamin',
                'satuan' => 'strip',
                'harga_beli' => 2000,
                'harga_jual' => 3500,
                'stok' => 150,
                'stok_minimum' => 20,
                'tanggal_expired' => now()->addMonths(24)->toDateString(),
                'prioritas_owner' => 2,
            ],
            [
                'supplier' => 'PT Anugerah Pharmindo Lestari',
                'kode_obat' => 'OBT-014',
                'nama_obat' => 'Loratadine 10mg',
                'kategori' => 'Antihistamin',
                'satuan' => 'strip',
                'harga_beli' => 7000,
                'harga_jual' => 11000,
                'stok' => 85,
                'stok_minimum' => 15,
                'tanggal_expired' => now()->addMonths(13)->toDateString(),
                'prioritas_owner' => 3,
            ],

            // Pencernaan (Maag & Diare)
            [
                'supplier' => 'PT Dos Ni Roha',
                'kode_obat' => 'OBT-015',
                'nama_obat' => 'Omeprazole 20mg',
                'kategori' => 'Pencernaan',
                'satuan' => 'strip',
                'harga_beli' => 13000,
                'harga_jual' => 19500,
                'stok' => 80,
                'stok_minimum' => 15,
                'tanggal_expired' => now()->addMonths(6)->toDateString(),
                'prioritas_owner' => 4,
            ],
            [
                'supplier' => 'PT Dos Ni Roha',
                'kode_obat' => 'OBT-016',
                'nama_obat' => 'Lansoprazole 30mg',
                'kategori' => 'Pencernaan',
                'satuan' => 'strip',
                'harga_beli' => 15000,
                'harga_jual' => 23000,
                'stok' => 75,
                'stok_minimum' => 15,
                'tanggal_expired' => now()->addMonths(7)->toDateString(),
                'prioritas_owner' => 4,
            ],
            [
                'supplier' => 'PT Kimia Farma Trading',
                'kode_obat' => 'OBT-017',
                'nama_obat' => 'Antasida Doen Tablet Chew',
                'kategori' => 'Pencernaan',
                'satuan' => 'strip',
                'harga_beli' => 3000,
                'harga_jual' => 5000,
                'stok' => 120,
                'stok_minimum' => 20,
                'tanggal_expired' => now()->addMonths(18)->toDateString(),
                'prioritas_owner' => 4,
            ],
            [
                'supplier' => 'PT Anugerah Pharmindo Lestari',
                'kode_obat' => 'OBT-018',
                'nama_obat' => 'Promag Tablet Chewable',
                'kategori' => 'Pencernaan',
                'satuan' => 'strip',
                'harga_beli' => 7500,
                'harga_jual' => 11500,
                'stok' => 110,
                'stok_minimum' => 30,
                'tanggal_expired' => now()->addMonths(14)->toDateString(),
                'prioritas_owner' => 5,
            ],
            [
                'supplier' => 'PT Dos Ni Roha',
                'kode_obat' => 'OBT-019',
                'nama_obat' => 'Loperamide 2mg (Imodium)',
                'kategori' => 'Pencernaan',
                'satuan' => 'strip',
                'harga_beli' => 5000,
                'harga_jual' => 8500,
                'stok' => 70,
                'stok_minimum' => 10,
                'tanggal_expired' => now()->addMonths(2)->toDateString(),
                'prioritas_owner' => 2,
            ],
            [
                'supplier' => 'PT Anugerah Pharmindo Lestari',
                'kode_obat' => 'OBT-020',
                'nama_obat' => 'Diapet Kapsul Diare',
                'kategori' => 'Pencernaan',
                'satuan' => 'strip',
                'harga_beli' => 4000,
                'harga_jual' => 6500,
                'stok' => 95,
                'stok_minimum' => 15,
                'tanggal_expired' => now()->addMonths(16)->toDateString(),
                'prioritas_owner' => 3,
            ],
            [
                'supplier' => 'PT Anugerah Pharmindo Lestari',
                'kode_obat' => 'OBT-021',
                'nama_obat' => 'Entrostop Tablet Diare',
                'kategori' => 'Pencernaan',
                'satuan' => 'strip',
                'harga_beli' => 7000,
                'harga_jual' => 10500,
                'stok' => 85,
                'stok_minimum' => 20,
                'tanggal_expired' => now()->addMonths(12)->toDateString(),
                'prioritas_owner' => 4,
            ],
            [
                'supplier' => 'PT Kimia Farma Trading',
                'kode_obat' => 'OBT-022',
                'nama_obat' => 'Ranitidine 150mg',
                'kategori' => 'Pencernaan',
                'satuan' => 'strip',
                'harga_beli' => 6000,
                'harga_jual' => 9500,
                'stok' => 75,
                'stok_minimum' => 15,
                'tanggal_expired' => now()->addMonths(10)->toDateString(),
                'prioritas_owner' => 3,
            ],

            // Diabetes & Hipertensi
            [
                'supplier' => 'PT Enseval Putera Megatrading',
                'kode_obat' => 'OBT-023',
                'nama_obat' => 'Metformin 500mg',
                'kategori' => 'Diabetes',
                'satuan' => 'strip',
                'harga_beli' => 9000,
                'harga_jual' => 14500,
                'stok' => 100,
                'stok_minimum' => 25,
                'tanggal_expired' => now()->addMonths(15)->toDateString(),
                'prioritas_owner' => 5,
            ],
            [
                'supplier' => 'PT Enseval Putera Megatrading',
                'kode_obat' => 'OBT-024',
                'nama_obat' => 'Glibenclamide 5mg',
                'kategori' => 'Diabetes',
                'satuan' => 'strip',
                'harga_beli' => 5000,
                'harga_jual' => 8000,
                'stok' => 85,
                'stok_minimum' => 15,
                'tanggal_expired' => now()->addMonths(14)->toDateString(),
                'prioritas_owner' => 4,
            ],
            [
                'supplier' => 'PT Anugerah Pharmindo Lestari',
                'kode_obat' => 'OBT-025',
                'nama_obat' => 'Amlodipine 5mg',
                'kategori' => 'Hipertensi',
                'satuan' => 'strip',
                'harga_beli' => 7500,
                'harga_jual' => 12000,
                'stok' => 110,
                'stok_minimum' => 30,
                'tanggal_expired' => now()->addMonths(11)->toDateString(),
                'prioritas_owner' => 5,
            ],
            [
                'supplier' => 'PT Anugerah Pharmindo Lestari',
                'kode_obat' => 'OBT-026',
                'nama_obat' => 'Amlodipine 10mg',
                'kategori' => 'Hipertensi',
                'satuan' => 'strip',
                'harga_beli' => 11000,
                'harga_jual' => 17000,
                'stok' => 95,
                'stok_minimum' => 25,
                'tanggal_expired' => now()->addMonths(13)->toDateString(),
                'prioritas_owner' => 5,
            ],
            [
                'supplier' => 'PT Kimia Farma Trading',
                'kode_obat' => 'OBT-027',
                'nama_obat' => 'Captopril 25mg',
                'kategori' => 'Hipertensi',
                'satuan' => 'strip',
                'harga_beli' => 4500,
                'harga_jual' => 7500,
                'stok' => 90,
                'stok_minimum' => 20,
                'tanggal_expired' => now()->addMonths(17)->toDateString(),
                'prioritas_owner' => 4,
            ],

            // Kolesterol & Asam Urat
            [
                'supplier' => 'PT Enseval Putera Megatrading',
                'kode_obat' => 'OBT-028',
                'nama_obat' => 'Simvastatin 10mg',
                'kategori' => 'Kolesterol',
                'satuan' => 'strip',
                'harga_beli' => 8500,
                'harga_jual' => 13500,
                'stok' => 85,
                'stok_minimum' => 20,
                'tanggal_expired' => now()->addMonths(12)->toDateString(),
                'prioritas_owner' => 5,
            ],
            [
                'supplier' => 'PT Enseval Putera Megatrading',
                'kode_obat' => 'OBT-029',
                'nama_obat' => 'Simvastatin 20mg',
                'kategori' => 'Kolesterol',
                'satuan' => 'strip',
                'harga_beli' => 14000,
                'harga_jual' => 21000,
                'stok' => 80,
                'stok_minimum' => 15,
                'tanggal_expired' => now()->addMonths(16)->toDateString(),
                'prioritas_owner' => 4,
            ],
            [
                'supplier' => 'PT Kimia Farma Trading',
                'kode_obat' => 'OBT-030',
                'nama_obat' => 'Allopurinol 100mg',
                'kategori' => 'Asam Urat',
                'satuan' => 'strip',
                'harga_beli' => 5000,
                'harga_jual' => 8500,
                'stok' => 75,
                'stok_minimum' => 20,
                'tanggal_expired' => now()->addMonths(14)->toDateString(),
                'prioritas_owner' => 4,
            ],

            // Pernapasan & Batuk Flu
            [
                'supplier' => 'CV Sumber Sehat Medika',
                'kode_obat' => 'OBT-031',
                'nama_obat' => 'Salbutamol 2mg',
                'kategori' => 'Pernapasan',
                'satuan' => 'strip',
                'harga_beli' => 6000,
                'harga_jual' => 10000,
                'stok' => 70,
                'stok_minimum' => 15,
                'tanggal_expired' => now()->addMonths(9)->toDateString(),
                'prioritas_owner' => 4,
            ],
            [
                'supplier' => 'PT Dos Ni Roha',
                'kode_obat' => 'OBT-032',
                'nama_obat' => 'Ventolin Inhaler 200 Dose',
                'kategori' => 'Pernapasan',
                'satuan' => 'botol',
                'harga_beli' => 115000,
                'harga_jual' => 145000,
                'stok' => 50,
                'stok_minimum' => 8,
                'tanggal_expired' => now()->addMonths(18)->toDateString(),
                'prioritas_owner' => 5,
            ],
            [
                'supplier' => 'PT Kimia Farma Trading',
                'kode_obat' => 'OBT-033',
                'nama_obat' => 'Ambroxol 30mg Tablet',
                'kategori' => 'Pernapasan',
                'satuan' => 'strip',
                'harga_beli' => 4500,
                'harga_jual' => 7000,
                'stok' => 90,
                'stok_minimum' => 20,
                'tanggal_expired' => now()->addMonths(19)->toDateString(),
                'prioritas_owner' => 3,
            ],
            [
                'supplier' => 'PT Anugerah Pharmindo Lestari',
                'kode_obat' => 'OBT-034',
                'nama_obat' => 'Mixagrip Flu & Batuk',
                'kategori' => 'Flu & Batuk',
                'satuan' => 'strip',
                'harga_beli' => 3500,
                'harga_jual' => 5500,
                'stok' => 120,
                'stok_minimum' => 25,
                'tanggal_expired' => now()->addMonths(21)->toDateString(),
                'prioritas_owner' => 4,
            ],
            [
                'supplier' => 'PT Anugerah Pharmindo Lestari',
                'kode_obat' => 'OBT-035',
                'nama_obat' => 'Tremenza Tablet Flu',
                'kategori' => 'Flu & Batuk',
                'satuan' => 'strip',
                'harga_beli' => 18000,
                'harga_jual' => 26000,
                'stok' => 80,
                'stok_minimum' => 15,
                'tanggal_expired' => now()->addMonths(10)->toDateString(),
                'prioritas_owner' => 4,
            ],
            [
                'supplier' => 'PT Anugerah Pharmindo Lestari',
                'kode_obat' => 'OBT-036',
                'nama_obat' => 'Rhinos SR Kapsul',
                'kategori' => 'Flu & Batuk',
                'satuan' => 'strip',
                'harga_beli' => 65000,
                'harga_jual' => 88000,
                'stok' => 60,
                'stok_minimum' => 10,
                'tanggal_expired' => now()->addMonths(13)->toDateString(),
                'prioritas_owner' => 5,
            ],
            [
                'supplier' => 'CV Sumber Sehat Medika',
                'kode_obat' => 'OBT-037',
                'nama_obat' => 'Komix Batuk Hitam Sachet',
                'kategori' => 'Flu & Batuk',
                'satuan' => 'sachet',
                'harga_beli' => 1800,
                'harga_jual' => 3000,
                'stok' => 150,
                'stok_minimum' => 30,
                'tanggal_expired' => now()->addMonths(18)->toDateString(),
                'prioritas_owner' => 3,
            ],

            // Sirup Anak
            [
                'supplier' => 'CV Sumber Sehat Medika',
                'kode_obat' => 'OBT-038',
                'nama_obat' => 'Sanmol Sirup Anak 60ml',
                'kategori' => 'Sirup Anak',
                'satuan' => 'botol',
                'harga_beli' => 16000,
                'harga_jual' => 23000,
                'stok' => 90,
                'stok_minimum' => 15,
                'tanggal_expired' => now()->addMonths(14)->toDateString(),
                'prioritas_owner' => 5,
            ],
            [
                'supplier' => 'CV Sumber Sehat Medika',
                'kode_obat' => 'OBT-039',
                'nama_obat' => 'OBH Combi Anak Batuk Flu 100ml',
                'kategori' => 'Sirup Anak',
                'satuan' => 'botol',
                'harga_beli' => 19000,
                'harga_jual' => 27000,
                'stok' => 85,
                'stok_minimum' => 15,
                'tanggal_expired' => now()->addMonths(12)->toDateString(),
                'prioritas_owner' => 4,
            ],

            // Vitamin & Suplemen / Herbal
            [
                'supplier' => 'CV Sumber Sehat Medika',
                'kode_obat' => 'OBT-040',
                'nama_obat' => 'Vitamin C 500mg Botol 100s',
                'kategori' => 'Vitamin',
                'satuan' => 'botol',
                'harga_beli' => 20000,
                'harga_jual' => 30000,
                'stok' => 100,
                'stok_minimum' => 15,
                'tanggal_expired' => now()->addMonths(20)->toDateString(),
                'prioritas_owner' => 3,
            ],
            [
                'supplier' => 'PT Anugerah Pharmindo Lestari',
                'kode_obat' => 'OBT-041',
                'nama_obat' => 'Neurobion Forte Pink Strip',
                'kategori' => 'Vitamin',
                'satuan' => 'strip',
                'harga_beli' => 38000,
                'harga_jual' => 52000,
                'stok' => 95,
                'stok_minimum' => 20,
                'tanggal_expired' => now()->addMonths(15)->toDateString(),
                'prioritas_owner' => 5,
            ],
            [
                'supplier' => 'PT Anugerah Pharmindo Lestari',
                'kode_obat' => 'OBT-042',
                'nama_obat' => 'Sangobion Kapsul Strip',
                'kategori' => 'Vitamin',
                'satuan' => 'strip',
                'harga_beli' => 18000,
                'harga_jual' => 26000,
                'stok' => 85,
                'stok_minimum' => 15,
                'tanggal_expired' => now()->addMonths(16)->toDateString(),
                'prioritas_owner' => 4,
            ],
            [
                'supplier' => 'PT Anugerah Pharmindo Lestari',
                'kode_obat' => 'OBT-043',
                'nama_obat' => 'Tolak Angin Cair Box 12s',
                'kategori' => 'Herbal',
                'satuan' => 'box',
                'harga_beli' => 38000,
                'harga_jual' => 50000,
                'stok' => 90,
                'stok_minimum' => 15,
                'tanggal_expired' => now()->addMonths(18)->toDateString(),
                'prioritas_owner' => 4,
            ],
            [
                'supplier' => 'PT Anugerah Pharmindo Lestari',
                'kode_obat' => 'OBT-044',
                'nama_obat' => 'Imboost Force Tablet Strip',
                'kategori' => 'Vitamin',
                'satuan' => 'strip',
                'harga_beli' => 62000,
                'harga_jual' => 82000,
                'stok' => 70,
                'stok_minimum' => 12,
                'tanggal_expired' => now()->addMonths(11)->toDateString(),
                'prioritas_owner' => 5,
            ],
            [
                'supplier' => 'PT Anugerah Pharmindo Lestari',
                'kode_obat' => 'OBT-045',
                'nama_obat' => 'CDR Effervescent Tube 10s',
                'kategori' => 'Vitamin',
                'satuan' => 'tube',
                'harga_beli' => 42000,
                'harga_jual' => 58000,
                'stok' => 75,
                'stok_minimum' => 10,
                'tanggal_expired' => now()->addMonths(14)->toDateString(),
                'prioritas_owner' => 4,
            ],

            // Obat Luar & Salep & Steril
            [
                'supplier' => 'PT Kimia Farma Trading',
                'kode_obat' => 'OBT-046',
                'nama_obat' => 'Bioplacenton Salep Luka 15g',
                'kategori' => 'Obat Luar',
                'satuan' => 'tube',
                'harga_beli' => 22000,
                'harga_jual' => 31000,
                'stok' => 90,
                'stok_minimum' => 15,
                'tanggal_expired' => now()->addMonths(10)->toDateString(),
                'prioritas_owner' => 5,
            ],
            [
                'supplier' => 'PT Kimia Farma Trading',
                'kode_obat' => 'OBT-047',
                'nama_obat' => 'Betadine Solusio Antiseptik 60ml',
                'kategori' => 'Obat Luar',
                'satuan' => 'botol',
                'harga_beli' => 28000,
                'harga_jual' => 39000,
                'stok' => 80,
                'stok_minimum' => 12,
                'tanggal_expired' => now()->addMonths(22)->toDateString(),
                'prioritas_owner' => 4,
            ],
            [
                'supplier' => 'PT Anugerah Pharmindo Lestari',
                'kode_obat' => 'OBT-048',
                'nama_obat' => 'Counterpain Salep Nyeri 30g',
                'kategori' => 'Obat Luar',
                'satuan' => 'tube',
                'harga_beli' => 34000,
                'harga_jual' => 46000,
                'stok' => 75,
                'stok_minimum' => 12,
                'tanggal_expired' => now()->addMonths(17)->toDateString(),
                'prioritas_owner' => 4,
            ],
            [
                'supplier' => 'PT Anugerah Pharmindo Lestari',
                'kode_obat' => 'OBT-049',
                'nama_obat' => 'Voltaren Emulgel Nyeri 20g',
                'kategori' => 'Obat Luar',
                'satuan' => 'tube',
                'harga_beli' => 58000,
                'harga_jual' => 76000,
                'stok' => 60,
                'stok_minimum' => 10,
                'tanggal_expired' => now()->addMonths(9)->toDateString(),
                'prioritas_owner' => 5,
            ],
            [
                'supplier' => 'PT Dos Ni Roha',
                'kode_obat' => 'OBT-050',
                'nama_obat' => 'Insto Regular Tetes Mata 7.5ml',
                'kategori' => 'Kesehatan Mata',
                'satuan' => 'botol',
                'harga_beli' => 14000,
                'harga_jual' => 20000,
                'stok' => 90,
                'stok_minimum' => 15,
                'tanggal_expired' => now()->addMonths(13)->toDateString(),
                'prioritas_owner' => 4,
            ],
            [
                'supplier' => 'PT Dos Ni Roha',
                'kode_obat' => 'OBT-051',
                'nama_obat' => 'Rohto Tetes Mata Iritasi 10ml',
                'kategori' => 'Kesehatan Mata',
                'satuan' => 'botol',
                'harga_beli' => 15500,
                'harga_jual' => 22000,
                'stok' => 85,
                'stok_minimum' => 15,
                'tanggal_expired' => now()->addMonths(15)->toDateString(),
                'prioritas_owner' => 3,
            ],
            [
                'supplier' => 'PT Kimia Farma Trading',
                'kode_obat' => 'OBT-052',
                'nama_obat' => 'Dexamethasone 0.5mg',
                'kategori' => 'Antiinflamasi',
                'satuan' => 'strip',
                'harga_beli' => 3000,
                'harga_jual' => 5000,
                'stok' => 95,
                'stok_minimum' => 20,
                'tanggal_expired' => now()->addMonths(16)->toDateString(),
                'prioritas_owner' => 4,
            ],
        ];

        foreach ($obat as $item) {
            $supplierName = $item['supplier'];
            unset($item['supplier']);

            Medicine::updateOrCreate(
                ['kode_obat' => $item['kode_obat']],
                [
                    ...$item,
                    'supplier_id' => $suppliers[$supplierName] ?? $defaultSupplier->id,
                ]
            );
        }
    }
}
